sudo: false
language: python
python:
  - "2.7"
install:
  - pip install tox
  - pip install codecov
script:
  - tox
before_install:
  # грязный хак от тревиса https://docs.travis-ci.com/user/private-dependencies/#API-Token
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
after_success:
  - codecov --token=$CODECOV_TOKEN
