sudo: false
language: python
python:
  - 2.7
#  - 3.5
#  - nightly
install:
  - pip install tox
  - pip install codecov
script:
  - tox
after_success:
  - codecov --token=$CODECOV_TOKEN
before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
notifications:
    email:
        recipients:
            - taras@drapalyuk.com
        on_failure: always
