
language: python
python:
  - 2.7
#  - 3.5
#  - nightly
install:
  - pip install tox
script:
  - tox
notifications:
    email:
        recipients:
            - taras@drapalyuk.com
        on_failure: always
